version: '3.4'
services:


  rasa-server:
    #image: rasa-bot:latest
    working_dir: /app
    build: "./"
    restart: always
    volumes:
    - ./actions:/app/actions
    - ./data:/app/data
    command: rasa train && rasa run --enable-api --cors "*" --auth-token xyz -p 5055
    ports:
    - '5055:5055'
    #- '5006:5005'
    networks:
    - all

  rasa-actions-server:
    image: rasa-bot:latest
    working_dir: /app
    build: "./"
    restart: always
    volumes:
    - ./actions:/app/actions
    - ./utils:/app/utils
    command: ["rasa", "run", "actions"]
    ports:
    - '5055:5055'
    networks:
    - all
  django-server:
    #image: rasa-bot:latest
    working_dir: /app
    build: "./"
    restart: always
    volumes:
    - ./rasadjango:/app/rasadjango
    - ./rasaweb:/app/rasaweb
    - ./static:/app/static
    - ./templates:/app/templates
    - ./manage.py:/app/manage.py
    command: python manage.py runserver --noreload 0.0.0.0:8000
    ports:
    #- '5055:5055'
    - '8000:8000'
    networks:
    - all

networks:
  all:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
